# Site settings
title: Zack Gemmell
email: zack.gemmell@gmail.com
description: "Product designer living in San Diego."
url: "http://zgemmell.com/"
github:  https://github.com/zackgemmell
linkedin: https://www.linkedin.com/in/zackgemmell/
name: Zack Gemmell


# Build settings
markdown: kramdown
theme: minima

exclude:
  - Gemfile
  - Gemfile.lock

exclude: [vendor]

plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-redirect-from

include: ['_pages']