# Site settings
title: The Portfolio of Zack Gemmell
email: zack.gemmell@gmail.com
description: "Product designer and prototyper living in San Diego."
url: "http://zgemmell.com/asana/"
github:  https://github.com/zackgemmell
linkedin: https://www.linkedin.com/in/zackgemmell/
baseurl: /asana

name: Zack Gemmell

safe: true
lsi: false
source: /asana/

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

  